---

# this playbook will standup a nora infrastructure

- hosts: all
  become: True
  gather_facts: False
  tasks:
    - include_tasks: tasks/install_python.yml

- hosts: all
  become: True
  gather_facts: True
  tasks:
    - include_tasks: tasks/install_ntp.yml
    - include_tasks: tasks/install_salt_deps.yml

- hosts: infra-master
  become: True
  roles:
    - role: salt-master 
      become: True
    - role: kubernetes
      become: True

- hosts: salt-minion
  roles:
    - role: salt-minion
      become: True

- hosts: openstack-controller
  roles:
    - role: openstack-controller
      become: True

- hosts: contrail
  roles:
    - role: contrail
      become: True

