---

# this playbook will standup a standalone opencontrail + kolla + saltstack server. More servers can be added later with other tools

- hosts: all
  become: True
  gather_facts: False
  tasks:
    - include_tasks: tasks/install_python.yml

- hosts: all
  become: True
  gather_facts: True
  tasks:
    - include_tasks: tasks/install_ntp.yml

- hosts: infra-master
  become: True
  roles:
    - role: k8
      become: True

