---

# this playbook will standup a standalone kubernetes + opencontrail + saltstack server. More servers can be added later with other tools

- hosts: infra-master
  gather_facts: False
  become: True
  tasks:
    - include_tasks: tasks/install_python.yml
    - include_tasks: tasks/install_salt_deps_for_git.yml

- hosts: infra-master
  roles:
    - role: infra-master
      become: True
    - role: kubernetes
      become: True
