---
###################
# Ceph options
####################
# These options must be UUID4 values in string format
# XXXXXXXX-XXXX-4XXX-XXXX-XXXXXXXXXXXX
ceph_cluster_fsid: {{ contrail_password }}
# for backward compatible consideration, rbd_secret_uuid is only used for nova,
# cinder_rbd_secret_uuid is used for cinder
rbd_secret_uuid: {{ contrail_password }}
cinder_rbd_secret_uuid: {{ contrail_password }}

###################
# Database options
####################
database_password: {{ contrail_password }}

####################
# Docker options
####################
# This should only be set if you require a password for your Docker registry
docker_registry_password: {{ contrail_password }}

####################
# OpenStack options
####################
aodh_database_password: {{ contrail_password }}
aodh_keystone_password: {{ contrail_password }}

barbican_database_password: {{ contrail_password }}
barbican_keystone_password: {{ contrail_password }}
barbican_p11_password: {{ contrail_password }}
barbican_crypto_key: {{ contrail_password }}
barbican_crypto_password: {{ contrail_password }}

keystone_admin_password: {{ contrail_password }}
keystone_database_password: {{ contrail_password }}

grafana_database_password: {{ contrail_password }}
grafana_admin_password: {{ contrail_password }}

glance_database_password: {{ contrail_password }}
glance_keystone_password: {{ contrail_password }}

gnocchi_database_password: {{ contrail_password }}
gnocchi_keystone_password: {{ contrail_password }}

karbor_database_password: {{ contrail_password }}
karbor_keystone_password: {{ contrail_password }}
karbor_openstack_infra_id: {{ contrail_password }}

kuryr_keystone_password: {{ contrail_password }}

nova_database_password: {{ contrail_password }}
nova_api_database_password: {{ contrail_password }}
nova_keystone_password: {{ contrail_password }}

placement_keystone_password: {{ contrail_password }}

neutron_database_password: {{ contrail_password }}
neutron_keystone_password: {{ contrail_password }}
#metadata_secret: {{ contrail_password }}

cinder_database_password: {{ contrail_password }}
cinder_keystone_password: {{ contrail_password }}

cloudkitty_database_password: {{ contrail_password }}
cloudkitty_keystone_password: {{ contrail_password }}

panko_database_password: {{ contrail_password }}
panko_keystone_password: {{ contrail_password }}

freezer_database_password: {{ contrail_password }}
freezer_keystone_password: {{ contrail_password }}

sahara_database_password: {{ contrail_password }}
sahara_keystone_password: {{ contrail_password }}

designate_database_password: {{ contrail_password }}
designate_pool_manager_database_password: {{ contrail_password }}
designate_keystone_password: {{ contrail_password }}
# This option must be UUID4 value in string format
designate_pool_id: {{ contrail_password }}
# This option must be HMAC-MD5 value in string format
designate_rndc_key: {{ contrail_password }}

swift_keystone_password: {{ contrail_password }}
swift_hash_path_suffix: {{ contrail_password }}
swift_hash_path_prefix: {{ contrail_password }}

heat_database_password: {{ contrail_password }}
heat_keystone_password: {{ contrail_password }}
heat_domain_admin_password: {{ contrail_password }}

murano_database_password: {{ contrail_password }}
murano_keystone_password: {{ contrail_password }}

ironic_database_password: {{ contrail_password }}
ironic_keystone_password: {{ contrail_password }}

ironic_inspector_database_password: {{ contrail_password }}
ironic_inspector_keystone_password: {{ contrail_password }}

magnum_database_password: {{ contrail_password }}
magnum_keystone_password: {{ contrail_password }}

mistral_database_password: {{ contrail_password }}
mistral_keystone_password: {{ contrail_password }}

trove_database_password: {{ contrail_password }}
trove_keystone_password: {{ contrail_password }}

ceilometer_database_password: {{ contrail_password }}
ceilometer_keystone_password: {{ contrail_password }}

watcher_database_password: {{ contrail_password }}
watcher_keystone_password: {{ contrail_password }}

congress_database_password: {{ contrail_password }}
congress_keystone_password: {{ contrail_password }}

rally_database_password: {{ contrail_password }}

senlin_database_password: {{ contrail_password }}
senlin_keystone_password: {{ contrail_password }}

solum_database_password: {{ contrail_password }}
solum_keystone_password: {{ contrail_password }}

horizon_secret_key: {{ contrail_password }}
horizon_database_password: {{ contrail_password }}

telemetry_secret_key: {{ contrail_password }}

manila_database_password: {{ contrail_password }}
manila_keystone_password: {{ contrail_password }}

octavia_database_password: {{ contrail_password }}
octavia_keystone_password: {{ contrail_password }}
octavia_ca_password: {{ contrail_password }}

searchlight_keystone_password: {{ contrail_password }}

tacker_database_password: {{ contrail_password }}
tacker_keystone_password: {{ contrail_password }}

memcache_secret_key: {{ contrail_password }}

nova_ssh_key:
  private_key: '-----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEApQX9JLwpO8Ov1Qd5+Ul5sOTXgDQkmGGIKeB+reF+iAQ8XDaw
      9w3YlB4I42dtkyGQRXSwSPbxm60O2d7h/ZmBhkjGfiIFNbwSR64xTYK9LZBaZ1sw
      edsUWJqEvmM1Asut+ytvmbmJ2yyf/B9H6zRiREsaKi/dubdor0AcLbanis8fk0XP
      bsZRmrg0lx0dEt1UfKionBq38YgCfyU2Tk6CS/rWwbk2b4r/QNPb1SmiLGJvbrND
      JbR+2FaBtR9LiHHsL3AtqYWDSS1zLVQThtIdKSvpfXz/hOJ9sN9mRZnWJ7teSzfW
      1tCtjCFHZuVV4V+W3R8o8Fj65ncu3czIM9io7wIDAQABAoIBABnN/e+onKoDx5MA
      QEqC+sx2fFxHyxEo7yndOPHnuOl8ABRLWRDI0X0X1Tv6CGBhdzXlMUu3kcBOJ2xa
      Nex5/I8LAj7nAvmMFy+uRXdhYkOltv1CfSoQ3/Wa8/bxfHCbePE1sZXQNYZYTAwY
      uB5HarZTKBxAr+NCktQUqlNbpIdH68rkTF6PWN4dfmFpnfrGY0GvGO3++GPug/Id
      PaWKX/8zmfobxi40ufUxaxynqhXdom9EgZTZah2yagxO57Wck5Y7B52M+1TReH0v
      rbzGYnc9J4v4czTjqQxlhDYCv83zdz+wrNDlTS/3/Cg2C7qDnHN1pdGJn1kUYlLb
      BPyMtIECgYEA1fZBLwvLsz1KQAVdNQtdXGgJPAznzOL8GV9BIXdjhqLARYa7IGzF
      8cGE7CXacIo0Q73JjD3y0hTmWcOwUdd6oJ5rnjSpQoMO8TUt9pSvQyKSJMAMxcIC
      WC/5MVYvZEojOgraM23DVUYwuGKrpVQheLqlLgfdJlwxyyFd5hhuaBkCgYEAxXI/
      zHsRNxvr8cyA+IGx+q0+omPV1M05k/mw7Waa6DyfqKtcZ7KPSmbX0lsbEOu62m6X
      W4r0Qt5Nygxje+Br+VxLKLjkbLHQosb7rFKOyUxbDEGJBt4VKBmdpfVv5Sh0PVpY
      7emy3QmoT9xmwYZDvTvN4fKwkSAPi+x2SAnJWkcCgYAON83/FVaU85ayiGi4NKgg
      kt1CO01QBSlhej32vltDwB7sv9ZBgljpBsYRdzZ70gNFGSCCjD9NjIv+HQ3jcmE4
      uS5HlhJFVDYy+yixwRGgcXSqsoRmw8yqFY4GpEaD8JVEryHu1vVq/j4QkqX7V4rd
      3fFKDMW6XdgFOpNlzevQSQKBgQDALhT1BbBa8H12K/Q4bZx7fxbg3sWpzFtHsZhJ
      aj5K338ToD9f24fnBjT5VZ4BmUCVDWGbQ6O+Vjxm9in60BSocPHi4BvNxEFrvrwG
      HZFHU1+njT4/hfgXwN8WQs+3v+lsMj0uzPJAfP7rRH5rzTCvxr79NsgvaYJYUj9K
      nOP0TwKBgDkEWE97I48832NkbNYAjlqWlpgwjmU/wfQg7agESd//vMbX1Nx0IDiT
      TsUmakj/eyEGbTDPA6Nbb9+nMWU7wZs0DwklPcVoaE60dRLawD58KuOqD8t4g4Pf
      agPIL3NcrbZiz4VVfYH+ZHHKICdfQ0t6IC7VaLC6ZdbSf7SbIt0I
      -----END RSA PRIVATE KEY-----'

  public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClBf0kvCk7w6/VB3n5SXmw5NeANCSYYYgp4H6t4X6IBDxcNrD3DdiUHgjjZ22TIZBFdLBI9vGbrQ7Z3uH9mYGGSMZ+IgU1vBJHrjFNgr0tkFpnWzB52xRYmoS+YzUCy637K2+ZuYnbLJ/8H0frNGJESxoqL925t2ivQBwttqeKzx+TRc9uxlGauDSXHR0S3VR8qKicGrfxiAJ/JTZOToJL+tbBuTZviv9A09vVKaIsYm9us0MltH7YVoG1H0uIcewvcC2phYNJLXMtVBOG0h0pK+l9fP+E4n2w32ZFmdYnu15LN9bW0K2MIUdm5VXhX5bdHyjwWPrmdy7dzMgz2Kjv root@server-manager-lite.sm-domain.com'


kolla_ssh_key:
  private_key: '-----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEApQX9JLwpO8Ov1Qd5+Ul5sOTXgDQkmGGIKeB+reF+iAQ8XDaw
      9w3YlB4I42dtkyGQRXSwSPbxm60O2d7h/ZmBhkjGfiIFNbwSR64xTYK9LZBaZ1sw
      edsUWJqEvmM1Asut+ytvmbmJ2yyf/B9H6zRiREsaKi/dubdor0AcLbanis8fk0XP
      bsZRmrg0lx0dEt1UfKionBq38YgCfyU2Tk6CS/rWwbk2b4r/QNPb1SmiLGJvbrND
      JbR+2FaBtR9LiHHsL3AtqYWDSS1zLVQThtIdKSvpfXz/hOJ9sN9mRZnWJ7teSzfW
      1tCtjCFHZuVV4V+W3R8o8Fj65ncu3czIM9io7wIDAQABAoIBABnN/e+onKoDx5MA
      QEqC+sx2fFxHyxEo7yndOPHnuOl8ABRLWRDI0X0X1Tv6CGBhdzXlMUu3kcBOJ2xa
      Nex5/I8LAj7nAvmMFy+uRXdhYkOltv1CfSoQ3/Wa8/bxfHCbePE1sZXQNYZYTAwY
      uB5HarZTKBxAr+NCktQUqlNbpIdH68rkTF6PWN4dfmFpnfrGY0GvGO3++GPug/Id
      PaWKX/8zmfobxi40ufUxaxynqhXdom9EgZTZah2yagxO57Wck5Y7B52M+1TReH0v
      rbzGYnc9J4v4czTjqQxlhDYCv83zdz+wrNDlTS/3/Cg2C7qDnHN1pdGJn1kUYlLb
      BPyMtIECgYEA1fZBLwvLsz1KQAVdNQtdXGgJPAznzOL8GV9BIXdjhqLARYa7IGzF
      8cGE7CXacIo0Q73JjD3y0hTmWcOwUdd6oJ5rnjSpQoMO8TUt9pSvQyKSJMAMxcIC
      WC/5MVYvZEojOgraM23DVUYwuGKrpVQheLqlLgfdJlwxyyFd5hhuaBkCgYEAxXI/
      zHsRNxvr8cyA+IGx+q0+omPV1M05k/mw7Waa6DyfqKtcZ7KPSmbX0lsbEOu62m6X
      W4r0Qt5Nygxje+Br+VxLKLjkbLHQosb7rFKOyUxbDEGJBt4VKBmdpfVv5Sh0PVpY
      7emy3QmoT9xmwYZDvTvN4fKwkSAPi+x2SAnJWkcCgYAON83/FVaU85ayiGi4NKgg
      kt1CO01QBSlhej32vltDwB7sv9ZBgljpBsYRdzZ70gNFGSCCjD9NjIv+HQ3jcmE4
      uS5HlhJFVDYy+yixwRGgcXSqsoRmw8yqFY4GpEaD8JVEryHu1vVq/j4QkqX7V4rd
      3fFKDMW6XdgFOpNlzevQSQKBgQDALhT1BbBa8H12K/Q4bZx7fxbg3sWpzFtHsZhJ
      aj5K338ToD9f24fnBjT5VZ4BmUCVDWGbQ6O+Vjxm9in60BSocPHi4BvNxEFrvrwG
      HZFHU1+njT4/hfgXwN8WQs+3v+lsMj0uzPJAfP7rRH5rzTCvxr79NsgvaYJYUj9K
      nOP0TwKBgDkEWE97I48832NkbNYAjlqWlpgwjmU/wfQg7agESd//vMbX1Nx0IDiT
      TsUmakj/eyEGbTDPA6Nbb9+nMWU7wZs0DwklPcVoaE60dRLawD58KuOqD8t4g4Pf
      agPIL3NcrbZiz4VVfYH+ZHHKICdfQ0t6IC7VaLC6ZdbSf7SbIt0I
      -----END RSA PRIVATE KEY-----'
  public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClBf0kvCk7w6/VB3n5SXmw5NeANCSYYYgp4H6t4X6IBDxcNrD3DdiUHgjjZ22TIZBFdLBI9vGbrQ7Z3uH9mYGGSMZ+IgU1vBJHrjFNgr0tkFpnWzB52xRYmoS+YzUCy637K2+ZuYnbLJ/8H0frNGJESxoqL925t2ivQBwttqeKzx+TRc9uxlGauDSXHR0S3VR8qKicGrfxiAJ/JTZOToJL+tbBuTZviv9A09vVKaIsYm9us0MltH7YVoG1H0uIcewvcC2phYNJLXMtVBOG0h0pK+l9fP+E4n2w32ZFmdYnu15LN9bW0K2MIUdm5VXhX5bdHyjwWPrmdy7dzMgz2Kjv root@server-manager-lite.sm-domain.com'

keystone_ssh_key:
  private_key: '-----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEApQX9JLwpO8Ov1Qd5+Ul5sOTXgDQkmGGIKeB+reF+iAQ8XDaw
      9w3YlB4I42dtkyGQRXSwSPbxm60O2d7h/ZmBhkjGfiIFNbwSR64xTYK9LZBaZ1sw
      edsUWJqEvmM1Asut+ytvmbmJ2yyf/B9H6zRiREsaKi/dubdor0AcLbanis8fk0XP
      bsZRmrg0lx0dEt1UfKionBq38YgCfyU2Tk6CS/rWwbk2b4r/QNPb1SmiLGJvbrND
      JbR+2FaBtR9LiHHsL3AtqYWDSS1zLVQThtIdKSvpfXz/hOJ9sN9mRZnWJ7teSzfW
      1tCtjCFHZuVV4V+W3R8o8Fj65ncu3czIM9io7wIDAQABAoIBABnN/e+onKoDx5MA
      QEqC+sx2fFxHyxEo7yndOPHnuOl8ABRLWRDI0X0X1Tv6CGBhdzXlMUu3kcBOJ2xa
      Nex5/I8LAj7nAvmMFy+uRXdhYkOltv1CfSoQ3/Wa8/bxfHCbePE1sZXQNYZYTAwY
      uB5HarZTKBxAr+NCktQUqlNbpIdH68rkTF6PWN4dfmFpnfrGY0GvGO3++GPug/Id
      PaWKX/8zmfobxi40ufUxaxynqhXdom9EgZTZah2yagxO57Wck5Y7B52M+1TReH0v
      rbzGYnc9J4v4czTjqQxlhDYCv83zdz+wrNDlTS/3/Cg2C7qDnHN1pdGJn1kUYlLb
      BPyMtIECgYEA1fZBLwvLsz1KQAVdNQtdXGgJPAznzOL8GV9BIXdjhqLARYa7IGzF
      8cGE7CXacIo0Q73JjD3y0hTmWcOwUdd6oJ5rnjSpQoMO8TUt9pSvQyKSJMAMxcIC
      WC/5MVYvZEojOgraM23DVUYwuGKrpVQheLqlLgfdJlwxyyFd5hhuaBkCgYEAxXI/
      zHsRNxvr8cyA+IGx+q0+omPV1M05k/mw7Waa6DyfqKtcZ7KPSmbX0lsbEOu62m6X
      W4r0Qt5Nygxje+Br+VxLKLjkbLHQosb7rFKOyUxbDEGJBt4VKBmdpfVv5Sh0PVpY
      7emy3QmoT9xmwYZDvTvN4fKwkSAPi+x2SAnJWkcCgYAON83/FVaU85ayiGi4NKgg
      kt1CO01QBSlhej32vltDwB7sv9ZBgljpBsYRdzZ70gNFGSCCjD9NjIv+HQ3jcmE4
      uS5HlhJFVDYy+yixwRGgcXSqsoRmw8yqFY4GpEaD8JVEryHu1vVq/j4QkqX7V4rd
      3fFKDMW6XdgFOpNlzevQSQKBgQDALhT1BbBa8H12K/Q4bZx7fxbg3sWpzFtHsZhJ
      aj5K338ToD9f24fnBjT5VZ4BmUCVDWGbQ6O+Vjxm9in60BSocPHi4BvNxEFrvrwG
      HZFHU1+njT4/hfgXwN8WQs+3v+lsMj0uzPJAfP7rRH5rzTCvxr79NsgvaYJYUj9K
      nOP0TwKBgDkEWE97I48832NkbNYAjlqWlpgwjmU/wfQg7agESd//vMbX1Nx0IDiT
      TsUmakj/eyEGbTDPA6Nbb9+nMWU7wZs0DwklPcVoaE60dRLawD58KuOqD8t4g4Pf
      agPIL3NcrbZiz4VVfYH+ZHHKICdfQ0t6IC7VaLC6ZdbSf7SbIt0I
      -----END RSA PRIVATE KEY-----'
  public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClBf0kvCk7w6/VB3n5SXmw5NeANCSYYYgp4H6t4X6IBDxcNrD3DdiUHgjjZ22TIZBFdLBI9vGbrQ7Z3uH9mYGGSMZ+IgU1vBJHrjFNgr0tkFpnWzB52xRYmoS+YzUCy637K2+ZuYnbLJ/8H0frNGJESxoqL925t2ivQBwttqeKzx+TRc9uxlGauDSXHR0S3VR8qKicGrfxiAJ/JTZOToJL+tbBuTZviv9A09vVKaIsYm9us0MltH7YVoG1H0uIcewvcC2phYNJLXMtVBOG0h0pK+l9fP+E4n2w32ZFmdYnu15LN9bW0K2MIUdm5VXhX5bdHyjwWPrmdy7dzMgz2Kjv root@server-manager-lite.sm-domain.com'

bifrost_ssh_key:
  private_key: '-----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEApQX9JLwpO8Ov1Qd5+Ul5sOTXgDQkmGGIKeB+reF+iAQ8XDaw
      9w3YlB4I42dtkyGQRXSwSPbxm60O2d7h/ZmBhkjGfiIFNbwSR64xTYK9LZBaZ1sw
      edsUWJqEvmM1Asut+ytvmbmJ2yyf/B9H6zRiREsaKi/dubdor0AcLbanis8fk0XP
      bsZRmrg0lx0dEt1UfKionBq38YgCfyU2Tk6CS/rWwbk2b4r/QNPb1SmiLGJvbrND
      JbR+2FaBtR9LiHHsL3AtqYWDSS1zLVQThtIdKSvpfXz/hOJ9sN9mRZnWJ7teSzfW
      1tCtjCFHZuVV4V+W3R8o8Fj65ncu3czIM9io7wIDAQABAoIBABnN/e+onKoDx5MA
      QEqC+sx2fFxHyxEo7yndOPHnuOl8ABRLWRDI0X0X1Tv6CGBhdzXlMUu3kcBOJ2xa
      Nex5/I8LAj7nAvmMFy+uRXdhYkOltv1CfSoQ3/Wa8/bxfHCbePE1sZXQNYZYTAwY
      uB5HarZTKBxAr+NCktQUqlNbpIdH68rkTF6PWN4dfmFpnfrGY0GvGO3++GPug/Id
      PaWKX/8zmfobxi40ufUxaxynqhXdom9EgZTZah2yagxO57Wck5Y7B52M+1TReH0v
      rbzGYnc9J4v4czTjqQxlhDYCv83zdz+wrNDlTS/3/Cg2C7qDnHN1pdGJn1kUYlLb
      BPyMtIECgYEA1fZBLwvLsz1KQAVdNQtdXGgJPAznzOL8GV9BIXdjhqLARYa7IGzF
      8cGE7CXacIo0Q73JjD3y0hTmWcOwUdd6oJ5rnjSpQoMO8TUt9pSvQyKSJMAMxcIC
      WC/5MVYvZEojOgraM23DVUYwuGKrpVQheLqlLgfdJlwxyyFd5hhuaBkCgYEAxXI/
      zHsRNxvr8cyA+IGx+q0+omPV1M05k/mw7Waa6DyfqKtcZ7KPSmbX0lsbEOu62m6X
      W4r0Qt5Nygxje+Br+VxLKLjkbLHQosb7rFKOyUxbDEGJBt4VKBmdpfVv5Sh0PVpY
      7emy3QmoT9xmwYZDvTvN4fKwkSAPi+x2SAnJWkcCgYAON83/FVaU85ayiGi4NKgg
      kt1CO01QBSlhej32vltDwB7sv9ZBgljpBsYRdzZ70gNFGSCCjD9NjIv+HQ3jcmE4
      uS5HlhJFVDYy+yixwRGgcXSqsoRmw8yqFY4GpEaD8JVEryHu1vVq/j4QkqX7V4rd
      3fFKDMW6XdgFOpNlzevQSQKBgQDALhT1BbBa8H12K/Q4bZx7fxbg3sWpzFtHsZhJ
      aj5K338ToD9f24fnBjT5VZ4BmUCVDWGbQ6O+Vjxm9in60BSocPHi4BvNxEFrvrwG
      HZFHU1+njT4/hfgXwN8WQs+3v+lsMj0uzPJAfP7rRH5rzTCvxr79NsgvaYJYUj9K
      nOP0TwKBgDkEWE97I48832NkbNYAjlqWlpgwjmU/wfQg7agESd//vMbX1Nx0IDiT
      TsUmakj/eyEGbTDPA6Nbb9+nMWU7wZs0DwklPcVoaE60dRLawD58KuOqD8t4g4Pf
      agPIL3NcrbZiz4VVfYH+ZHHKICdfQ0t6IC7VaLC6ZdbSf7SbIt0I
      -----END RSA PRIVATE KEY-----'
  public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClBf0kvCk7w6/VB3n5SXmw5NeANCSYYYgp4H6t4X6IBDxcNrD3DdiUHgjjZ22TIZBFdLBI9vGbrQ7Z3uH9mYGGSMZ+IgU1vBJHrjFNgr0tkFpnWzB52xRYmoS+YzUCy637K2+ZuYnbLJ/8H0frNGJESxoqL925t2ivQBwttqeKzx+TRc9uxlGauDSXHR0S3VR8qKicGrfxiAJ/JTZOToJL+tbBuTZviv9A09vVKaIsYm9us0MltH7YVoG1H0uIcewvcC2phYNJLXMtVBOG0h0pK+l9fP+E4n2w32ZFmdYnu15LN9bW0K2MIUdm5VXhX5bdHyjwWPrmdy7dzMgz2Kjv root@server-manager-lite.sm-domain.com'

####################
# Gnocchi options
####################
gnocchi_project_id: {{ contrail_password }}
gnocchi_resource_id: {{ contrail_password }}
gnocchi_user_id: {{ contrail_password }}

####################
# RabbitMQ options
####################
rabbitmq_password: {{ contrail_password }}
rabbitmq_cluster_cookie: {{ contrail_password }}

####################
# HAProxy options
####################
haproxy_password: {{ contrail_password }}
keepalived_password: {{ contrail_password }}

####################
# Kibana options
####################
kibana_password: {{ contrail_password }}

####################
# etcd options
####################
etcd_cluster_token: {{ contrail_password }}
