kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fission-storage-pvc
  namespace: fission
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
